---
name: Build

on:
  push:
    branches:
      - master
      - "bugfix-release/*"
      - "release/*"
  pull_request:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type"
        required: true
        type: choice
        default: "auto"
        options:
          - auto
          - nightly
          - stable
  merge_group:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  C2_ENABLE_LTO: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/bugfix-release/') || startsWith(github.ref, 'refs/heads/release/') }}
  CHATTERINO_REQUIRE_CLEAN_GIT: On
  CHATTERINO_BUILD_TYPE: ${{ case(inputs.buildType != '', inputs.buildType, 'auto') }}

jobs:
  build:
    name: "Build ${{ matrix.os }}, Qt ${{ matrix.qt-version }} (LTO:${{ matrix.force-lto }}, crashpad:${{ case(matrix.skip-crashpad, 'off', 'on') }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # macOS
          - os: macos-26
            qt-version: 6.11.1
            force-lto: false
            skip-artifact: false
            skip-crashpad: false

      fail-fast: false
    env:
      C2_ENABLE_LTO: ${{ matrix.force-lto }}
      C2_ENABLE_CRASHPAD: ${{ matrix.skip-crashpad == false }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ case(github.event_name == 'pull_request', github.event.pull_request.head.sha, '') }} # checkout pull request HEAD if PR triggered this job
          submodules: recursive
          fetch-depth: 0 # allows for tags access
          persist-credentials: false

      - name: Determine build type
        id: build-type
        shell: bash
        run: |
          if [ "${CHATTERINO_BUILD_TYPE}" = "auto" ]; then
            if git describe --exact-match --match 'v*'; then
              echo "Auto - found release tag format"
              echo "NIGHTLY_BUILD=Off" >> "$GITHUB_OUTPUT"
            else
              echo "Auto - did not find release tag format"
              echo "NIGHTLY_BUILD=On" >> "$GITHUB_OUTPUT"
            fi
          elif [ "${CHATTERINO_BUILD_TYPE}" = "nightly" ]; then
            echo "Override to nightly"
            echo "NIGHTLY_BUILD=On" >> "$GITHUB_OUTPUT"
          elif [ "${CHATTERINO_BUILD_TYPE}" = "stable" ]; then
            echo "Override to stable"
            echo "NIGHTLY_BUILD=Off" >> "$GITHUB_OUTPUT"
          else
            echo "Error: no build type variable set"
            exit 1
          fi

      - name: Install Qt6
        if: startsWith(matrix.qt-version, '6.')
        uses: jurplel/install-qt-action@a9c63c7c123f3069cff414e7e482d95dfa9d8125 # v4.4.1
        with:
          cache: true
          cache-key-prefix: ${{ runner.os }}-QtCache-${{ matrix.qt-version }}-v2
          modules: qtimageformats
          version: ${{ matrix.qt-version }}

      # MACOS
      - name: Install dependencies (MacOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          # brew install openssl rapidjson p7zip create-dmg cmake tree boost hunspell
          brew install openssl rapidjson p7zip create-dmg tree boost hunspell
        shell: bash

      - name: Build (MacOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          mkdir build
          cd build
          cmake \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
              -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl \
              -DUSE_PRECOMPILED_HEADERS=OFF \
              -DCHATTERINO_LTO="$C2_ENABLE_LTO" \
              -DFORCE_JSON_GENERATION=Off \
              -DCHATTERINO_NIGHTLY_BUILD=${{ steps.build-type.outputs.NIGHTLY_BUILD }} \
              -DCHATTERINO_SPELLCHECK=On \
              ..
          make -j"$(sysctl -n hw.logicalcpu)"
        shell: bash

      - name: Package (MacOS)
        if: startsWith(matrix.os, 'macos')
        env:
          OUTPUT_DMG_PATH: chatterino-macos-Qt-${{ matrix.qt-version}}.dmg
        run: |
          ls -la
          pwd
          ls -la build || true
          cd build
          ./../.CI/MacDeploy.sh
          ./../.CI/CreateDMG.sh
        shell: bash

      - name: Upload artifact (MacOS)
        if: startsWith(matrix.os, 'macos')
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: chatterino-macos-Qt-${{ matrix.qt-version }}.dmg
          path: build/chatterino-macos-Qt-${{ matrix.qt-version }}.dmg
